version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: .Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: web_django
    volumes:
      - .:/code
      - .env:/code/.env
    ports:
    - 8000:8000
