# Generated by Django 3.2.9 on 2021-12-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('work_experience', models.JSONField()),
                ('total_experience', models.IntegerField(default=0)),
            ],
        ),
    ]
