# Generated by Django 3.2.9 on 2021-12-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='month_remainder',
            field=models.IntegerField(default=0),
        ),
    ]
